### ISSUE TITLE
Abort blending strategy in paper

### ISSUE THREAD

**Issue by luckynote** [tkat0/PyTorch_BlazeFace#10]
I don't understand the blending strategy in paper. 
If you known, please get it.
Thanks!

**Comment by liangxiao05** [comment]
@luckynote ,no codes or implements seen since now. I think maybe it's implemented like this  :
Box A ,score Sa  ;Box B,score  Sb
Sa > Sb ,and IoU（A，B）>iou_nms_threshold
1)original NMS:
Sb ->0, Box output is A
2) blending strategy :
Box output is weightA*BoxA+weightB*BoxB,
maybe weightA =Sa/(Sa+Sb)，I'm not sure about it ,for reference only.

**Comment by luckynote** [comment]
ok, thank you!
